import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { MaxWidthWrapper } from "@/components/MaxWidthWrapper";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="h-full">
            <body
                className={cn(
                    "relative h-full font-san antialiased",
                    inter.className
                )}
            >
                <main className="relative flex flex-col min-h-screen">
                    <NavBar></NavBar>
                    <div className="flex-grow flex-1">{children}</div>
                    <div>Footer in layout.tsx</div>
                </main>
            </body>
        </html>
    );
}
